root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp/main.exe ./cmd"
  bin = "tmp/main.exe"
  delay = 1000
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor", ".git"]
  stop_on_error = true

[misc]
  clean_on_exit = true