services:
  pg:
    image: postgres:18.1
    restart: always
    environment:
      POSTGRES_USER: "IvanSuslov"
      POSTGRES_PASSWORD: "2556625"
      POSTGRES_DB: "tracker_calories"
    ports:
      - "5433:5432"

  app:
    build: .
    restart: always
    environment:
      DB_CONFIG: "host=pg user=IvanSuslov password=2556625 dbname=tracker_calories port=5432 sslmode=disable"
      COST: "14"
      SECRET: "tykcrykhcf54xjide5475tg"
      PORT: "8080"
    ports:
<<<<<<< HEAD
      - "8080:8080"
=======
      - "8081:8080"
>>>>>>> 02bb01d591b176e08639bd48871facaaad222664
